// Generated by scripts/generate-api-types.sh from OpenAPI request-body
// `required` arrays. Do not edit by hand.
export interface ApiRequestBodyRequiredKeys {
	"/api/items": {
		post: "title";
	};
	"/api/items/{item_id}": {
		patch: never;
	};
	"/api/items/{item_id}/progress": {
		post: "note";
	};
	"/api/capture": {
		post: "raw_text";
	};
	"/api/items/{item_id}/enrich": {
		post: "additional_context";
	};
	"/api/items/{item_id}/assist-update": {
		post: "note";
	};
	"/api/tools/{name}": {
		patch: "enabled";
	};
	"/api/tools/install": {
		post: "openapi_url" | "instructions";
	};
	"/api/tools/{name}/summary/regenerate": {
		post: "expected_vid";
	};
	"/api/tools/{name}/revise": {
		post: "feedback" | "expected_vid";
	};
}
