/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture
         * @description Quick-capture raw text into a structured memory item.
         *
         *     The LLM call runs first, entirely outside any DB transaction. Only after a
         *     successful draft does ONE transaction create the item (source "llm-capture",
         *     stage quick, status from the model's suggestion) and seed its progress log.
         *     A 502 (unparseable or failed draft) therefore leaves the database untouched
         *     -- no partial rows -- because no write has happened yet. The blocking write
         *     itself runs in a threadpool (see _capture_persist), off the event loop.
         */
        post: operations["capture_api_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description List items (newest first) with optional filtering and pagination.
         */
        get: operations["list_items_api_items_get"];
        put?: never;
        /**
         * Create Item
         * @description Create an item and seed its history with the first progress entry.
         */
        post: operations["create_item_api_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item
         * @description Return a single item with its full progress history (oldest first).
         */
        get: operations["get_item_api_items__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Item
         * @description Delete an item; its progress entries are removed via cascade.
         */
        delete: operations["delete_item_api_items__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Item
         * @description Apply a partial update; bump `updated` only when a field is provided.
         */
        patch: operations["update_item_api_items__item_id__patch"];
        trace?: never;
    };
    "/api/items/{item_id}/assist-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assist Update Item
         * @description Assist an update: merge whitelisted section refreshes and append progress.
         *
         *     Same discipline as enrich (404 first, snapshot including `updated`, LLM
         *     outside any transaction, then a SINGLE conditional UPDATE guarded on the
         *     pre-await `updated` that resolves a mid-await writer to 409 or a delete to
         *     404, supersede-not-delete on history sections, writes only on a matching
         *     UPDATE, a response snapshot built from the written values after a race-wrapped
         *     flush before commit), but records a progress note without touching stage or
         *     returning gaps. The two blocking DB segments run in a threadpool (see
         *     _snapshot_item_for_ai / _assist_persist), off the event loop, using the
         *     dependency's session sequentially.
         */
        post: operations["assist_update_item_api_items__item_id__assist_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrich
         * @description Full-enrich an item: merge whitelisted section updates and append progress.
         *
         *     Order (constraint): 404 first, then snapshot the item fields (and its
         *     `updated` timestamp), then run the LLM strictly OUTSIDE any transaction (the
         *     read transaction is released before the await). Writes then land through a
         *     SINGLE conditional UPDATE guarded on the pre-await `updated`: merge the
         *     returned sections (untouched fields stay as they were; history-bearing
         *     sections are superseded, never overwritten) and, on a complete checklist,
         *     flip stage to full and graduate a still-capturing item
         *     (capture-quick/needs-enrichment) to active. If that UPDATE matches no row a
         *     writer touched the item mid-await and NOTHING is written -- a concurrent
         *     UPDATE (`updated` moved, row present) is 409, a concurrent DELETE (row gone)
         *     is 404. Closing the check with the write (rather than comparing `updated`
         *     then flushing) leaves no window a competing PATCH could slip through. On a
         *     match the progress entry is appended and the flush is race-wrapped so a
         *     delete landing in the remaining window still resolves to 404, not a 500. The
         *     response snapshot is built (after flush, before commit) from the values just
         *     written -- not a re-read. A 503/502/409 (or an item deleted mid-await) leaves
         *     the row unchanged. The two blocking DB segments run in a threadpool (see
         *     _snapshot_item_for_ai / _enrich_persist) so they never sit on the event loop;
         *     the session created by the dependency is used sequentially, never concurrently.
         */
        post: operations["enrich_api_items__item_id__enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Progress
         * @description Append a progress entry and bump the item's `updated` timestamp.
         */
        post: operations["add_progress_api_items__item_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Logs
         * @description List recent LLM interaction summaries, newest first, WITHOUT bodies.
         *
         *     Each summary carries only non-secret scalars (workflow, model name, timing,
         *     outcome, token usage) plus the attempt COUNT; the full prompt/response
         *     bodies load lazily via the by-id endpoint below. ``limit`` is bounded to
         *     [1, 500] at the query layer so an oversized page cannot be requested. The
         *     ring is process-wide and dies with the process, so an empty list is the
         *     normal state right after a restart.
         *
         *     That restart is also why the page needs ``process_token`` (see
         *     ``LlmLogListResponse``): the ids here are a per-process counter, and a client
         *     holding an OLDER one -- a ``?log=<id>`` deep link built from a cached job
         *     response -- must be able to find out that its id was re-issued rather than
         *     have this page open whatever now answers to the number.
         */
        get: operations["llm_logs_api_llm_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Log Detail
         * @description Return one full LLM interaction record, attempt bodies included.
         *
         *     404 (fixed, config-free ``{"detail": "LLM log not found"}``) when no record
         *     with that id is in the ring -- it was evicted past ``llm_log_max_entries``,
         *     the interaction is still in flight (recorded only on finish), or the id
         *     never existed. The bodies here can run to tens of KB per attempt (the full
         *     schema-injected prompt and the model's reply), which is why they are behind
         *     this by-id fetch rather than in the list above.
         */
        get: operations["llm_log_detail_api_llm_logs__log_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Status
         * @description Report whether an LLM endpoint is configured, the model name, and the
         *     char<->token ratio estimator's state.
         *
         *     Never returns the base URL or API key -- only the boolean, the non-secret
         *     model name (null when unconfigured), and the ratio snapshot. The model is run
         *     through the same `normalized_model` helper `generate_json` uses for the actual
         *     request, so a whitespace-padded override is never echoed back padded while the
         *     real call underneath sends the trimmed value. ``token_ratio`` is additive
         *     observability (P4): the estimator's window size and learned ratio (see
         *     afterthread.services.token_budget), carrying no config value.
         */
        get: operations["llm_status_api_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review
         * @description Group non-terminal items into disjoint buckets, oldest first per group.
         *
         *     The reviewable statuses are exactly the five non-terminal ones
         *     (models.STALE_ELIGIBLE_STATUSES); ``done`` and ``superseded`` are terminal
         *     and excluded entirely. A single query fetches every reviewable item so the
         *     buckets reflect one consistent snapshot. Building each bucket from its own
         *     query would let a status PATCH race between them and double-place or
         *     misplace an item (and the ORM identity map could hand back stale state for
         *     a row re-read across queries). Staleness is surfaced per item via
         *     ``MemoryItemRead.is_stale`` rather than as a separate group.
         */
        get: operations["review_api_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Installed Tools
         * @description List every installed tool package (valid or broken), in name order.
         *
         *     With the feature off (TOOLS_DIR unset) or nothing installed this is an
         *     empty list, NOT an error: the 工具 page distinguishes "feature off" via the
         *     install endpoint's 503, while an empty listing is a normal state.
         */
        get: operations["list_installed_tools_api_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install Tool
         * @description Queue a web-installer job; poll its state via the endpoint below.
         *
         *     202 + job id: the build is a long LLM session (minutes), far past any sane
         *     request timeout, so it runs as a background task. The 503 gate mirrors
         *     ``llm_not_configured``'s shape under its own code -- checked HERE, before a
         *     job is created, so a misconfigured deployment fails the submit itself
         *     rather than minting a job doomed to fail asynchronously. The LLM being
         *     unconfigured is deliberately NOT pre-checked: that state is already
         *     represented as a failed job with a friendly error (and its own AI 日誌
         *     record), and duplicating the gate here would just create two sources of
         *     truth for it.
         *
         *     409 when an install is already active: ``start_install_job`` admits only ONE
         *     queued/running install at a time (M7) and returns None when one is in
         *     flight, which maps to a fixed ``install_in_progress`` conflict here.
         */
        post: operations["install_tool_api_tools_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tool Job Status
         * @description One install/revise job's state. 404: unknown id, evicted, or a backend
         *     restart (jobs are process-local and unpersisted -- see tool_builder).
         *
         *     ONE endpoint for both kinds (D40): they share a job table, a single-flight
         *     admission and a response shape, so a second endpoint would only give the FE
         *     two identical pollers to keep in sync. The old `/install/{job_id}` spelling
         *     is REMOVED rather than aliased -- the FE and the backend ship in the same
         *     wheel, so there is no version skew for an alias to protect.
         *
         *     ``llm_log_process`` is stamped HERE rather than stored on the job, and that
         *     is sound STRUCTURALLY rather than by convention: the job table is in-process
         *     memory that dies with the log ring and its id counter (a restart 404s every
         *     job above), so any ``llm_log_id`` a job can still be served with was minted
         *     in THIS process. The sidecar needs its token written down because the FILE
         *     outlives the process; a job cannot. Both keep the same both-or-neither rule
         *     -- no id, no token -- so the pair can never disagree about whether there is a
         *     link worth vouching for (``ToolJobStatus``, ``tools.store_summary_meta``).
         */
        get: operations["tool_job_status_api_tools_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Installed Tool
         * @description Delete a tool package (its whole directory).
         *
         *     The registry's ``delete_tool`` re-validates the name AND resolved-path
         *     containment under the tools dir before it touches anything (the
         *     path-traversal / symlink-escape hard-block lives THERE, not in this router),
         *     and returns None for a missing package -> 404.
         *
         *     A request or inherited child holding the shared tools lock produces the
         *     distinct retryable ``ai_job_in_progress`` 409 without renaming or deleting
         *     anything. Otherwise the 200 response says ``removed`` after physical
         *     deletion or ``retained`` with the exact cleanup-failure path.
         */
        delete: operations["delete_installed_tool_api_tools__name__delete"];
        options?: never;
        head?: never;
        /**
         * Update Tool
         * @description Toggle a tool's ``enabled`` flag; returns the updated row.
         *
         *     ``set_enabled`` returning False collapses every did-not-happen case into one
         *     404 with a fixed detail: from the caller's view the addressable tool resource
         *     does not (usably) exist. Those cases are the feature being off, a name that
         *     resolves to nothing installed (or out of the tools dir, or through an internal
         *     alias), and a failed publish of the package's ``.afterthread.meta/state.json`` -- something
         *     that is not a regular file sitting at that name, an unwritable package
         *     directory, a package replaced between the resolve and the write.
         *
         *     The MANIFEST is not among them any more, and the difference is visible to a
         *     caller: since web-v5 P1 the toggle writes ``.afterthread.meta/state.json`` and never opens
         *     ``tool.json``, so a package whose manifest is a FIFO, oversized or unreadable
         *     now toggles successfully with a 200 while its row stays ``valid: false``. That
         *     is the intended behaviour (an operator can switch OFF a broken package, which
         *     is when they most want to) and it is what backend/README.md documents; a broken
         *     package is never advertised to the model either way.
         *
         *     The response is re-read from a fresh registry scan so it reports exactly what
         *     the next GET would.
         */
        patch: operations["update_tool_api_tools__name__patch"];
        trace?: never;
    };
    "/api/tools/{name}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revise Tool
         * @description Queue an AI revise job for one installed tool; poll it via `/jobs/{id}`.
         *
         *     202 + job id, exactly like the installer's submit and for the same reason: a
         *     revise IS a builder session (minutes of tool rounds and shell tests), so it
         *     cannot live inside a request. It therefore declares NEITHER 502 NOR 503: an
         *     LLM that is unconfigured or failing is represented as a FAILED job carrying a
         *     friendly error and its own AI 日誌 link, so the submit itself has no LLM
         *     outcome to report -- the same contract split test_ai_contract pins for the
         *     install submit (which does declare a 503, but for TOOLS_DIR, not the LLM).
         *     That 503 has no counterpart here: with TOOLS_DIR unset no name resolves, so
         *     this route's existence gate already answers 404.
         *
         *     ``start_revise_job`` first reserves the global slot, then resolves the package
         *     and compares the required ``expected_vid``.  Missing/aliased packages return
         *     404, a stale version returns ``version_mismatch``, and an occupied slot returns
         *     ``job_busy``.  Only a matching version is converted into a queued job, so a
         *     stale submit has neither an LLM charge nor even a pollable job id.
         */
        post: operations["revise_tool_api_tools__name__revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tool Summary
         * @description One tool's AI summary.
         *
         *     A tool with no sidecar is an all-null 200, NOT a 404 (see
         *     ``ToolSummaryDetail``): the resource being addressed is the tool's summary,
         *     and "this tool has no summary yet" is a normal state with its own UI. The
         *     404 is reserved for the tool itself not existing -- which, with TOOLS_DIR
         *     unset, is also what the whole feature being off looks like, and which an
         *     internal symlink alias is deliberately folded into (a summary must be read
         *     from the package it names, never from an aliased one).
         */
        get: operations["get_tool_summary_api_tools__name__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/summary/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Tool Summary
         * @description Re-run the summary generation for one tool and return the new sidecar.
         *
         *     SYNCHRONOUS, unlike the installer: this is one short single-turn generation
         *     (no tool loop, no shell, ordinary timeout), so it fits a request the way
         *     捕捉/補齊 do -- and it therefore follows THEIR error contract, declaring and
         *     raising the shared 503 ``llm_not_configured`` / 502 ``llm_upstream_error``
         *     from ``routers.ai``. The installer's asynchronous, job-shaped contract stays
         *     what it is precisely because a builder session cannot fit in a request.
         *
         *     Before the LLM is touched, a queued/running job is refused under the shared
         *     one-at-a-time builder/regenerate policy (409 ``job_busy``). After taking that
         *     slot, ``expected_vid`` is compared with the resolved current version; a stale
         *     caller gets ``version_mismatch`` without an LLM request.
         *
         *     The job gate TAKES a reservation rather than merely asking (R7-3), and the
         *     difference is what makes it a gate at all: this handler then awaits a full
         *     LLM round trip, and a bare ``any_job_active()`` read released the shared
         *     admission policy before that work finished. ``reserve_sync_operation`` decides
         *     and takes under the SAME lock ``_admit_job`` uses, so builder work is refused
         *     for the duration instead; the reservation is released in the ``finally`` below
         *     on every path, success or exception.
         *
         *     A generation that produced text but STORED nothing (``regenerate_summary``
         *     -> None: the package vanished mid-request, or the sidecar write was refused)
         *     is a 404 rather than a 200, so this route can never report a summary that
         *     the next GET will not find. That is the same fold the PATCH above applies to
         *     its own failed rewrite.
         */
        post: operations["regenerate_tool_summary_api_tools__name__summary_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools/{name}/versions/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Discard Tool Version
         * @description Discard the exact current version named by ``vid``.
         *
         *     The global slot is taken before resolving the route target, then the service
         *     re-resolves and compares ``vid`` only after taking the exclusive filesystem
         *     lock. That second placement is what prevents a route-level answer for V from
         *     authorizing an old V -> P publication after ``current`` has moved to Q. The
         *     response reports whether the former version's files were removed or retained,
         *     with the exact operator cleanup path in the latter case.
         */
        delete: operations["discard_tool_version_api_tools__name__versions__vid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssistUpdateRequest
         * @description Payload for AI assisted update: a progress note to record.
         */
        AssistUpdateRequest: {
            /** Note */
            note: string;
        };
        /**
         * AssistUpdateResponse
         * @description AI assisted-update result: the updated item.
         */
        AssistUpdateResponse: {
            item: components["schemas"]["MemoryItemRead"];
        };
        /**
         * CaptureRequest
         * @description Payload for AI quick capture: the raw discussion text to structure.
         */
        CaptureRequest: {
            /** Raw Text */
            raw_text: string;
        };
        /**
         * CaptureResponse
         * @description AI quick-capture result: the created item plus follow-up questions.
         */
        CaptureResponse: {
            item: components["schemas"]["MemoryItemRead"];
            /** Questions */
            questions: string[];
        };
        /**
         * EnrichRequest
         * @description Payload for AI full enrichment: new context to integrate.
         */
        EnrichRequest: {
            /** Additional Context */
            additional_context: string;
        };
        /**
         * EnrichResponse
         * @description AI enrichment result: the updated item plus remaining checklist gaps.
         */
        EnrichResponse: {
            /** Gaps */
            gaps: string[];
            item: components["schemas"]["MemoryItemRead"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemListResponse
         * @description Paginated list of memory items.
         */
        ItemListResponse: {
            /** Items */
            items: components["schemas"]["MemoryItemRead"][];
            /** Total */
            total: number;
        };
        /**
         * LLMStatus
         * @description Whether an LLM endpoint is configured, the model name, and the ratio state.
         *
         *     Deliberately excludes the base URL and API key -- only the boolean, the
         *     non-secret model name, and the char<->token ratio estimator's state are
         *     surfaced. ``model`` is genuinely null exactly when unconfigured, so its
         *     nullability is honest rather than a schema artifact. ``token_ratio`` is always
         *     present (the estimator always has a state to report, even cold-started).
         */
        LLMStatus: {
            /** Configured */
            configured: boolean;
            /** Model */
            model: string | null;
            token_ratio: components["schemas"]["LLMTokenRatio"];
        };
        /**
         * LLMTokenRatio
         * @description The live char<->token ratio estimator's public view (P4).
         *
         *     Surfaced on ``LLMStatus.token_ratio`` from
         *     afterthread.services.token_budget.snapshot(). ``samples`` is how many
         *     recent (chars, tokens) observations the rolling window holds; and
         *     ``tokens_per_char`` is the learned ratio rounded to 4dp, genuinely null while
         *     the window is still below the minimum-sample threshold (the cold-start default
         *     is in force and there is no observed ratio yet), so its nullability is honest.
         *     Carries no config value -- purely the internal estimator state.
         */
        LLMTokenRatio: {
            /** Samples */
            samples: number;
            /** Tokens Per Char */
            tokens_per_char: number | null;
        };
        /**
         * LlmLogAttempt
         * @description One request/response round: the full messages sent, the raw reply (or
         *     null), this attempt's OWN token usage, and a SAFE failure category (or
         *     null) if that attempt failed.
         *
         *     ``request_chars``/``response_chars`` are the STORED (post ``_stored_body``:
         *     UTF-8-safe, then size-capped) lengths, not the original size --
         *     ``response_chars`` is null exactly when ``response_content`` is (no
         *     response ever landed on this attempt), never 0 for that case. ``usage`` is
         *     THIS attempt's own reading, distinct from ``LlmLogBase.usage``'s
         *     interaction-level aggregate (see the module comment above). ``truncated``
         *     is true the moment ANY stored text on this attempt -- a request message, the
         *     response, or an advertised tool name -- was cut for size; the FE shows a
         *     small badge for it.
         *     ``tools_advertised`` is the NAMES of the tools this attempt offered the
         *     model, or null when it sent no ``tools`` parameter at all (see
         *     ``LlmAttempt`` in services/llm_log.py) -- declaring it here is what keeps it
         *     on the wire, since pydantic's default ``extra="ignore"`` would otherwise
         *     drop the key silently at the router's ``model_validate``. Like every other
         *     stored text here it has been through the log's redaction choke point, since
         *     a tool NAME can itself equal a registered secret value.
         */
        LlmLogAttempt: {
            /** Error */
            error: string | null;
            /** Request Chars */
            request_chars: number;
            /** Request Messages */
            request_messages: components["schemas"]["LlmLogMessage"][];
            /** Response Chars */
            response_chars: number | null;
            /** Response Content */
            response_content: string | null;
            /** Tools Advertised */
            tools_advertised?: string[] | null;
            /** Truncated */
            truncated: boolean;
            usage: components["schemas"]["LlmLogUsage"] | null;
        };
        /**
         * LlmLogDetail
         * @description A full log record: every attempt's request messages and response body.
         */
        LlmLogDetail: {
            /** Attempts */
            attempts: components["schemas"]["LlmLogAttempt"][];
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Model */
            model: string;
            /** Outcome */
            outcome: string | null;
            /** Started At */
            started_at: string;
            usage: components["schemas"]["LlmLogUsage"] | null;
            /** Workflow */
            workflow: string;
        };
        /**
         * LlmLogListResponse
         * @description Newest-first page of LLM interaction summaries.
         *
         *     ``process_token`` is the ANSWERING process's opaque identity for the id space
         *     every ``id`` on this page belongs to (``llm_log.process_token()``). Log ids
         *     are a per-process counter over a ring that dies with the process, so an id a
         *     client is HOLDING -- a ``?log=<id>`` deep link built from a job response the
         *     browser cached before a restart -- may name a completely different
         *     interaction here. Only the minting process's token can tell those apart, and
         *     this is the reading the AI 日誌 page compares a link's claim against.
         *
         *     It rides on the ENVELOPE rather than on the rows: it is a property of the
         *     process that answered, not of any record, so ``LlmLogBase`` (shared by the
         *     row and the detail, one entry per RECORD) would be both the wrong shape and
         *     50 copies of one string. The list is also the response that arrives BEFORE
         *     the page decides what a deep link points at, while the detail is fetched
         *     lazily per record -- an in-list link would have had to open the row first to
         *     learn whether it should have.
         */
        LlmLogListResponse: {
            /** Logs */
            logs: components["schemas"]["LlmLogSummary"][];
            /** Process Token */
            process_token: string;
        };
        /**
         * LlmLogMessage
         * @description One request message exactly as sent (role + full content).
         */
        LlmLogMessage: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /**
         * LlmLogSummary
         * @description One log row WITHOUT attempt bodies: ``attempts`` is the count only.
         *
         *     The list view shows how many attempts a call took; the full bodies (tens of
         *     KB each) load only on row expansion via the detail endpoint.
         */
        LlmLogSummary: {
            /** Attempts */
            attempts: number;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Model */
            model: string;
            /** Outcome */
            outcome: string | null;
            /** Started At */
            started_at: string;
            usage: components["schemas"]["LlmLogUsage"] | null;
            /** Workflow */
            workflow: string;
        };
        /**
         * LlmLogUsage
         * @description Token usage read defensively from a completion; any field may be null.
         */
        LlmLogUsage: {
            /** Completion Tokens */
            completion_tokens: number | null;
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /** Total Tokens */
            total_tokens: number | null;
        };
        /**
         * MemoryItemCreate
         * @description Payload for creating a memory item. Only ``title`` is mandatory.
         *
         *     title/tags/every section text field carry explicit upper bounds (see the
         *     ``_CRUD_*`` constants above) that MemoryItemContent itself does not, so
         *     MemoryItemRead is unaffected -- this is the source-side half of bounding
         *     the enrich/assist-update prompt header; the other half is the defensive
         *     per-field cap in ``memory_ai._serialize_item_for_prompt``.
         */
        MemoryItemCreate: {
            /**
             * Alternatives
             * @default
             */
            alternatives: string;
            /**
             * Assumptions
             * @default
             */
            assumptions: string;
            /**
             * Confidence
             * @default mixed
             */
            confidence: string;
            /**
             * Consequences
             * @default
             */
            consequences: string;
            /**
             * Constraints
             * @default
             */
            constraints: string;
            /**
             * Decisions
             * @default
             */
            decisions: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /**
             * Inferred
             * @default
             */
            inferred: string;
            /**
             * Known
             * @default
             */
            known: string;
            /**
             * Next Actions
             * @default
             */
            next_actions: string;
            /**
             * Open Questions
             * @default
             */
            open_questions: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Recovery Files
             * @default
             */
            recovery_files: string;
            /**
             * Recovery Keywords
             * @default
             */
            recovery_keywords: string;
            /**
             * Recovery People
             * @default
             */
            recovery_people: string;
            /**
             * Resume Trigger
             * @default
             */
            resume_trigger: string;
            /**
             * Risks
             * @default
             */
            risks: string;
            /**
             * Snapshot
             * @default
             */
            snapshot: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** @default quick */
            stage: components["schemas"]["MemoryStage"];
            /** @default capture-quick */
            status: components["schemas"]["MemoryStatus"];
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Unknown
             * @default
             */
            unknown: string;
            /**
             * Why Matters
             * @default
             */
            why_matters: string;
        };
        /**
         * MemoryItemRead
         * @description A memory item as returned by the API, including derived staleness.
         */
        MemoryItemRead: {
            /**
             * Alternatives
             * @default
             */
            alternatives: string;
            /**
             * Assumptions
             * @default
             */
            assumptions: string;
            /**
             * Confidence
             * @default mixed
             */
            confidence: string;
            /**
             * Consequences
             * @default
             */
            consequences: string;
            /**
             * Constraints
             * @default
             */
            constraints: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /**
             * Decisions
             * @default
             */
            decisions: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /** Id */
            id: number;
            /**
             * Inferred
             * @default
             */
            inferred: string;
            /**
             * Is Stale
             * @description True for a stale-eligible (non-terminal) item whose `updated` is
             *     past the configured threshold; always False for terminal items.
             *
             *     Stale-eligibility is the shared models.STALE_ELIGIBLE_STATUSES set
             *     (all five non-terminal statuses), not a schema-local subset.
             */
            readonly is_stale: boolean;
            /**
             * Known
             * @default
             */
            known: string;
            /**
             * Next Actions
             * @default
             */
            next_actions: string;
            /**
             * Open Questions
             * @default
             */
            open_questions: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Recovery Files
             * @default
             */
            recovery_files: string;
            /**
             * Recovery Keywords
             * @default
             */
            recovery_keywords: string;
            /**
             * Recovery People
             * @default
             */
            recovery_people: string;
            /**
             * Resume Trigger
             * @default
             */
            resume_trigger: string;
            /**
             * Risks
             * @default
             */
            risks: string;
            /**
             * Snapshot
             * @default
             */
            snapshot: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** @default quick */
            stage: components["schemas"]["MemoryStage"];
            /** @default capture-quick */
            status: components["schemas"]["MemoryStatus"];
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Unknown
             * @default
             */
            unknown: string;
            /**
             * Updated
             * Format: date-time
             */
            updated: string;
            /**
             * Why Matters
             * @default
             */
            why_matters: string;
        };
        /**
         * MemoryItemReadWithProgress
         * @description A memory item plus its full progress history (oldest first).
         */
        MemoryItemReadWithProgress: {
            /**
             * Alternatives
             * @default
             */
            alternatives: string;
            /**
             * Assumptions
             * @default
             */
            assumptions: string;
            /**
             * Confidence
             * @default mixed
             */
            confidence: string;
            /**
             * Consequences
             * @default
             */
            consequences: string;
            /**
             * Constraints
             * @default
             */
            constraints: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /**
             * Decisions
             * @default
             */
            decisions: string;
            /**
             * Evidence
             * @default
             */
            evidence: string;
            /** Id */
            id: number;
            /**
             * Inferred
             * @default
             */
            inferred: string;
            /**
             * Is Stale
             * @description True for a stale-eligible (non-terminal) item whose `updated` is
             *     past the configured threshold; always False for terminal items.
             *
             *     Stale-eligibility is the shared models.STALE_ELIGIBLE_STATUSES set
             *     (all five non-terminal statuses), not a schema-local subset.
             */
            readonly is_stale: boolean;
            /**
             * Known
             * @default
             */
            known: string;
            /**
             * Next Actions
             * @default
             */
            next_actions: string;
            /**
             * Open Questions
             * @default
             */
            open_questions: string;
            /** Progress */
            progress?: components["schemas"]["ProgressEntryRead"][];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Recovery Files
             * @default
             */
            recovery_files: string;
            /**
             * Recovery Keywords
             * @default
             */
            recovery_keywords: string;
            /**
             * Recovery People
             * @default
             */
            recovery_people: string;
            /**
             * Resume Trigger
             * @default
             */
            resume_trigger: string;
            /**
             * Risks
             * @default
             */
            risks: string;
            /**
             * Snapshot
             * @default
             */
            snapshot: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** @default quick */
            stage: components["schemas"]["MemoryStage"];
            /** @default capture-quick */
            status: components["schemas"]["MemoryStatus"];
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Unknown
             * @default
             */
            unknown: string;
            /**
             * Updated
             * Format: date-time
             */
            updated: string;
            /**
             * Why Matters
             * @default
             */
            why_matters: string;
        };
        /**
         * MemoryItemUpdate
         * @description Partial update payload; every field is optional via omission.
         *
         *     Every field is typed as its ordinary, non-nullable type with a
         *     `default_factory` that is never actually applied: the router
         *     (`update_item`) always calls `model_dump(exclude_unset=True)`, so an
         *     omitted field's default is never read or written, and pydantic v2 does
         *     not validate defaults unless `validate_default` is set (it isn't here).
         *     Using `default_factory` rather than a literal default is deliberate:
         *     pydantic v2 omits `default_factory`-sourced values from the generated
         *     JSON schema entirely, so every property below is optional but carries
         *     neither a `default` key nor `null` in its type. A literal default (e.g.
         *     `title: str = ""`) would instead surface as `"default": ""` in the
         *     OpenAPI schema; a client that honestly materialises schema defaults
         *     would then send `title=""` on every PATCH, tripping the not-blank
         *     validator or silently resetting fields the caller never meant to touch.
         *     The payoff is that the generated OpenAPI schema advertises each field's
         *     real type -- not nullable, no phantom default -- so an explicit JSON
         *     `null`, which no field here legitimately accepts, now fails ordinary
         *     type validation (422) instead of requiring a bespoke validator to catch
         *     it after the fact.
         */
        MemoryItemUpdate: {
            /** Alternatives */
            alternatives?: string;
            /** Assumptions */
            assumptions?: string;
            /** Confidence */
            confidence?: string;
            /** Consequences */
            consequences?: string;
            /** Constraints */
            constraints?: string;
            /** Decisions */
            decisions?: string;
            /** Evidence */
            evidence?: string;
            /** Inferred */
            inferred?: string;
            /** Known */
            known?: string;
            /** Next Actions */
            next_actions?: string;
            /** Open Questions */
            open_questions?: string;
            /** Rationale */
            rationale?: string;
            /** Recovery Files */
            recovery_files?: string;
            /** Recovery Keywords */
            recovery_keywords?: string;
            /** Recovery People */
            recovery_people?: string;
            /** Resume Trigger */
            resume_trigger?: string;
            /** Risks */
            risks?: string;
            /** Snapshot */
            snapshot?: string;
            /** Source */
            source?: string;
            stage?: components["schemas"]["MemoryStage"];
            status?: components["schemas"]["MemoryStatus"];
            /** Tags */
            tags?: string[];
            /** Title */
            title?: string;
            /** Unknown */
            unknown?: string;
            /** Why Matters */
            why_matters?: string;
        };
        /**
         * MemoryStage
         * @description Two-stage capture workflow marker.
         * @enum {string}
         */
        MemoryStage: "quick" | "full";
        /**
         * MemoryStatus
         * @description Lifecycle status of a memory item (see docs/methodology.md).
         * @enum {string}
         */
        MemoryStatus: "capture-quick" | "needs-enrichment" | "active" | "waiting" | "parked" | "done" | "superseded";
        /**
         * ProgressEntryCreate
         * @description Payload for appending a progress-log entry.
         */
        ProgressEntryCreate: {
            /** Note */
            note: string;
        };
        /**
         * ProgressEntryRead
         * @description A single progress-log entry.
         */
        ProgressEntryRead: {
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Id */
            id: number;
            /** Item Id */
            item_id: number;
            /** Note */
            note: string;
        };
        /**
         * ReviewResponse
         * @description Disjoint groups of items that need attention, oldest first per group.
         */
        ReviewResponse: {
            /** Active */
            active: components["schemas"]["MemoryItemRead"][];
            /** Needs Enrichment */
            needs_enrichment: components["schemas"]["MemoryItemRead"][];
            /** Parked */
            parked: components["schemas"]["MemoryItemRead"][];
            /** Waiting */
            waiting: components["schemas"]["MemoryItemRead"][];
        };
        /**
         * ToolDeleteResponse
         * @description Whether DELETE removed the files or retained a hidden parked tree.
         *
         *     ``retained_path`` is the exact operator-facing path when ``outcome`` is
         *     ``retained``; it is null after physical removal.
         */
        ToolDeleteResponse: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "removed" | "retained";
            /** Retained Path */
            retained_path: string | null;
            /** Retention Reason */
            retention_reason: ("durability_unconfirmed" | "cleanup_failed") | null;
        };
        /**
         * ToolDiscardResponse
         * @description Whether discard removed the former version or retained its files.
         */
        ToolDiscardResponse: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "removed" | "retained";
            /** Retained Path */
            retained_path: string | null;
            /** Retention Reason */
            retention_reason: ("durability_unconfirmed" | "cleanup_failed") | null;
        };
        /**
         * ToolExpectedVersionRequest
         * @description Required optimistic identity for a version-specific synchronous write.
         */
        ToolExpectedVersionRequest: {
            /** Expected Vid */
            expected_vid: string;
        };
        /**
         * ToolInstallAccepted
         * @description 202 body for a queued install or revise: the id to poll.
         */
        ToolInstallAccepted: {
            /** Job Id */
            job_id: string;
        };
        /**
         * ToolInstallRequest
         * @description Payload for the web installer: where the API lives, and what to build.
         *
         *     ``openapi_url`` is a pydantic HttpUrl, so a non-http(s) scheme or a
         *     hostless string is a 422 before any job starts. ``instructions`` shares the
         *     AI input bound every other AI free-text field carries (20000 chars,
         *     stripped-non-empty).
         *
         *     ``secret_name``/``secret_value`` are the OPTIONAL install-form secret (D36):
         *     a credential the user would otherwise paste into ``instructions`` (where it
         *     is recorded verbatim into the builder's AI-log prompts). Supplied HERE, the
         *     VALUE never enters the LLM conversation at all -- the backend injects it into
         *     run_shell's env so the builder can live-test the real API, and writes it into
         *     the finished tool's ``.env`` at install time (see tool_builder); llm_log
         *     redacts it besides. Both-or-neither, and the name must be a valid env-var
         *     name (it becomes one). ``secret_value`` is NEVER echoed back in any response
         *     (this is a request-only model, and no response schema carries the field).
         */
        ToolInstallRequest: {
            /** Instructions */
            instructions: string;
            /**
             * Openapi Url
             * Format: uri
             */
            openapi_url: string;
            /** Secret Name */
            secret_name?: string | null;
            /** Secret Value */
            secret_value?: string | null;
        };
        /**
         * ToolJobStatus
         * @description One install/revise job's visible state, as polled by the 工具 page.
         *
         *     ``state`` walks queued -> running -> succeeded | failed. ``error`` is the
         *     friendly zh-TW failure text (failed only); ``tool_name``/``summary`` are
         *     what the builder reported; ``llm_log_id`` links to the builder session's
         *     AI 日誌 record whenever a session actually ran, so both success and failure
         *     are debuggable from the UI. Jobs are process-local and unpersisted: after a
         *     backend restart every previous job id is a 404.
         *
         *     ``llm_log_process`` names the process whose id space that ``llm_log_id``
         *     belongs to -- the same both-or-neither pairing the sidecar keeps on disk
         *     (``tools.store_summary_meta``), for the same reason: log ids restart from
         *     zero in every process, so an id that OUTLIVES its process resolves to
         *     whatever now occupies the number. A job never outlives its process (the 404
         *     above), but a browser TAB does: the 工具 page stops polling a terminal job
         *     and keeps its response cached, so the outcome card -- and the ``查看 AI 日誌``
         *     link on it -- can still be on screen after a restart. The token travels with
         *     the link so the AI 日誌 page can refuse to resolve it (R9-1); the backend
         *     cannot catch this one alone, because it never SERVES a stale id.
         *
         *     One model for BOTH job kinds (D40 renamed it from ``ToolInstallJobStatus``
         *     without touching a field): an install writes a package into the tools
         *     directory and a revise adds a version to one and moves ``current``, and both
         *     report through one job table and one poll endpoint. ``env_keys`` names
         *     assignments from a builder-written ``.env`` that the backend stripped;
         *     values never enter the result.
         */
        ToolJobStatus: {
            /** Created At */
            created_at: string;
            /** Env Keys */
            env_keys: string[];
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Job Id */
            job_id: string;
            /** Llm Log Id */
            llm_log_id: number | null;
            /** Llm Log Process */
            llm_log_process: string | null;
            /** State */
            state: string;
            /** Summary */
            summary: string | null;
            /** Tool Name */
            tool_name: string | null;
        };
        /**
         * ToolListResponse
         * @description Every installed tool package, in name order.
         */
        ToolListResponse: {
            /** Tools */
            tools: components["schemas"]["ToolSummary"][];
        };
        /**
         * ToolReviseRequest
         * @description Payload for an AI revise job (D40): what the user wants changed.
         *
         *     ``feedback`` carries the SAME bound every other AI free-text input has
         *     (20000 chars, stripped-non-empty) and becomes the builder session's user
         *     turn. ``expected_vid`` is the required optimistic identity checked only
         *     after global single-flight admission. Which tool is being revised remains
         *     the PATH's job: the shared path regex validates its name.
         */
        ToolReviseRequest: {
            /** Expected Vid */
            expected_vid: string;
            /** Feedback */
            feedback: string;
        };
        /**
         * ToolSummary
         * @description One installed tool package as the 工具 page lists it.
         *
         *     ``valid=False`` rows carry the safe ``error`` reason from the registry scan
         *     (bad manifest, name mismatch, missing entry file); such a package is listed
         *     so it can be deleted, but is never advertised to the model or executable.
         *
         *     The summary text itself is fetched per tool on demand
         *     (``ToolSummaryDetail``), since it is far too long for a list row.
         */
        ToolSummary: {
            /** Current Vid */
            current_vid: string | null;
            /** Description */
            description: string | null;
            /** Enabled */
            enabled: boolean;
            /** Error */
            error: string | null;
            /**
             * Lineage
             * @enum {string}
             */
            lineage: "sole" | "usable" | "broken";
            /** Name */
            name: string;
            /** Valid */
            valid: boolean;
        };
        /**
         * ToolSummaryDetail
         * @description One tool's version summary
         *     (``versions/<vid>/.afterthread.meta/summary.json``), as the 工具 page reads it.
         *
         *     The three sidecar fields are nullable and all three are null together for the
         *     common, non-exceptional case of a tool with no sidecar: a hand-made package,
         *     or one whose summary generation has not run (or failed) yet. That is a 200,
         *     not a 404 -- the TOOL exists, it just has no summary -- so the page renders
         *     尚無總結 plus a 重新產生 action rather than an error. ``current_vid`` is
         *     always present and identifies the version that was actually read, so a
         *     response that crossed a pointer change cannot poison another version's cache.
         *
         *     ``llm_log_id`` links to the summary session's AI 日誌 record (the
         *     ``tool_summary`` workflow, distinct from the builder's ``tool_install``), so
         *     a wrong or missing summary is debuggable from the UI. It is null whenever the
         *     id on disk was minted by a PREVIOUS process: log ids are a per-process counter
         *     over a ring that is wiped on restart, so a persisted id only means something
         *     while that process lives (see ``routers.tools._summary_detail``, which nulls
         *     it rather than adding a fifth field -- a null here already means "no record to
         *     link", and the FE already renders exactly that).
         */
        ToolSummaryDetail: {
            /** Current Vid */
            current_vid: string;
            /** Llm Log Id */
            llm_log_id: number | null;
            /** Summary */
            summary: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * ToolUpdateRequest
         * @description PATCH payload for a tool: only the enabled toggle is mutable.
         */
        ToolUpdateRequest: {
            /** Enabled */
            enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capture_api_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description LLM upstream call failed or returned unusable output */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_upstream_error",
                     *         "message": "APIConnectionError: the upstream LLM request failed"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description LLM endpoint is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_not_configured",
                     *         "message": "The LLM endpoint is not configured."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_items_api_items_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["MemoryStatus"] | null;
                stage?: components["schemas"]["MemoryStage"] | null;
                tag?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryItemReadWithProgress"];
                };
            };
            /** @description Memory item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Memory item not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Memory item not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryItemRead"];
                };
            };
            /** @description Memory item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Memory item not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assist_update_item_api_items__item_id__assist_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistUpdateResponse"];
                };
            };
            /** @description Memory item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Memory item not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Item changed during AI processing (optimistic concurrency) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "conflict",
                     *         "message": "項目在 AI 處理期間已被其他變更修改。請重新載入後再試一次。"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description LLM upstream call failed or returned unusable output */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_upstream_error",
                     *         "message": "APIConnectionError: the upstream LLM request failed"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description LLM endpoint is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_not_configured",
                     *         "message": "The LLM endpoint is not configured."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    enrich_api_items__item_id__enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichResponse"];
                };
            };
            /** @description Memory item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Memory item not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Item changed during AI processing (optimistic concurrency) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "conflict",
                     *         "message": "項目在 AI 處理期間已被其他變更修改。請重新載入後再試一次。"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description LLM upstream call failed or returned unusable output */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_upstream_error",
                     *         "message": "APIConnectionError: the upstream LLM request failed"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description LLM endpoint is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_not_configured",
                     *         "message": "The LLM endpoint is not configured."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    add_progress_api_items__item_id__progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressEntryRead"];
                };
            };
            /** @description Memory item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Memory item not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_logs_api_llm_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_log_detail_api_llm_logs__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmLogDetail"];
                };
            };
            /** @description No LLM interaction log with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "LLM log not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_status_api_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMStatus"];
                };
            };
        };
    };
    review_api_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
        };
    };
    list_installed_tools_api_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolListResponse"];
                };
            };
        };
    };
    install_tool_api_tools_install_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolInstallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInstallAccepted"];
                };
            };
            /** @description Another install is already queued or running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "install_in_progress",
                     *         "message": "已有安裝正在進行中，請等待其完成"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Tool feature is not configured (TOOLS_DIR unset) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "tools_not_configured",
                     *         "message": "The tools directory is not configured."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    tool_job_status_api_tools_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolJobStatus"];
                };
            };
            /** @description Tool job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Tool job not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_installed_tool_api_tools__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolDeleteResponse"];
                };
            };
            /** @description Tool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Tool not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Version-specific tool operation conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The persistent tools lock path cannot be opened or locked */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "tools_lock_unavailable",
                     *         "message": "Tools lock /path/to/tools/.afterthread-tools.lck is unavailable: open failed: Permission denied. Repair ownership and owner read/write permissions on this existing inode; do not delete or recreate it."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    update_tool_api_tools__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolSummary"];
                };
            };
            /** @description Tool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Tool not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_tool_api_tools__name__revise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolReviseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolInstallAccepted"];
                };
            };
            /** @description Tool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Tool not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Version-specific tool operation conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tool_summary_api_tools__name__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolSummaryDetail"];
                };
            };
            /** @description Tool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Tool not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_tool_summary_api_tools__name__summary_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolExpectedVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolSummaryDetail"];
                };
            };
            /** @description Tool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Tool not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Version-specific tool operation conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description LLM upstream call failed or returned unusable output */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_upstream_error",
                     *         "message": "APIConnectionError: the upstream LLM request failed"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description LLM endpoint is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "llm_not_configured",
                     *         "message": "The LLM endpoint is not configured."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    discard_tool_version_api_tools__name__versions__vid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolDiscardResponse"];
                };
            };
            /** @description Tool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Tool not found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Version-specific tool operation conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The persistent tools lock path cannot be opened or locked */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": {
                     *         "code": "tools_lock_unavailable",
                     *         "message": "Tools lock /path/to/tools/.afterthread-tools.lck is unavailable: open failed: Permission denied. Repair ownership and owner read/write permissions on this existing inode; do not delete or recreate it."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
}
